package br.gov.caixa.sigcb.transaction;

import java.io.Serializable;

import br.gov.caixa.sigcb.util.FieldsByTransaction;
import br.gov.caixa.sigcb.util.LayoutTransaction;

/**
 * <B>Projeto: SIGCB</B><BR>
 * Componente responsável pelo controle da funcionalidade Banco de Títulos
 * <DL>
 * <DT><B>Criada em:</B>
 * <DD>01/09/2004</DD>
 * </DL>
 * 
 * @author Antonio Nestor Fusel - afusel@sao.politec.com.br
 */
public class BGJ1 implements LayoutTransaction, Serializable {

    public void setLayout(FieldsByTransaction fields) {

        fields.listSimpleTransaction.put("BGJ1-IDA",
                new String[] {
                              "tipoAcao",
                              "tpPessoa",
                              "cpfCnpj",
                              "nuPv",
                              "nuCOCLI",
                              "tipoCobranca",
                              "agContaCred",
                              "opContaCred",
                              "nuContaCred",
                              "dvContaCred",
                              "agContaDeb",
                              "opContaDeb",
                              "nuContaDeb",
                              "dvContaDeb",
                              "tpAplicativo",
                              "icPadrao",
                              "icAmbiente",
                              "tpTransmissao",
                              "van",
                              "codConnect",
                              "codInternet",
                              "ipConexao",
                              "noCedente",
                              "noRazaoSocial",
                              "idEndereco",
                              "noLogradouro",
                              "nuLocal",
                              "noComplemento",
                              "noBairro",
                              "noMunicipio",
                              "nuCep",
                              "sgUF"
                              });
        fields.listSimpleTransaction.put("BGJ1-VOLTA",
                new String[] {"codCedente",
		        		"tpCobranca",
		        	    "proAut",
		        	    "pzProt",
		        	    "pzDev",
		        	    "extTit",
		        	    "desExt",
		        	    "descrExt",
		        	    "extDebCred",
		        	    "desDebCred",
		        	    "descrExtDeb",
		        	    "invMen",
		        	    "tipJur",
		        	    "descrTipJur",
		        	    "perJur",
		        	    "perMulta",
		        	    "pzMulta",
		        	    "recCheque",
		        	    "bcoSac",
		        	    "modTit",
		        	    "cliSin",
		        	    "girCaixa",
		        	    "excAut",
		        	    "natureza",
		        	    "deNatureza",
		        	    "ramo",
		        	    "deRamo",
		        	    "setor",
		        	    "deSetor",
		        	    "porte",
		        	    "dePorte",
		        	    "filler",
		        	    "bcoCor",
		        	    "pvVinc",
		        	    "enVinc",
		        	    "cedCent",
		        	    "sitCed",
		        	    "icCobSemBlq",
		        	    "nuRede",
		        	    "tpAtividade",
		        	    "iof",
		        	    "valorDif",
		        	    "cocliSince",
		        	    "cedMasterPec",
		        	    "cedVincPec",
		        	    "dataVincPec",
		        	    "pvVincAnt",
		        	    "dtAltPvVinc",
		        	    "tpConta",
		        	    "unConta",
		        	    "opConta",
		        	    "nuConta",
		        	    "dvConta",
		        	    "pcRateio",
		        	    "vrRateio",
		        	    "tpContadeb",
		        	    "unContadeb",
		        	    "opContadeb",
		        	    "nuContadeb",
		        	    "dvContadeb",
		        	    "pcRateiodeb",
		        	    "vrRateiodeb",
		        	    //Guia Eletronico
		        	    "icAmbienteEle",
		        	    "tpAplicacao",
		        	    "dscAplicativo",
		        	    "coVrsApl",
		        	    "tpTran",
		        	    "dscTran",
		        	    "icPadraoEle",
		        	    "sit",
		        	    "icAtrVan",
		        	    "vanE",
		        	    "dscVan",
		        	    "icJunRet",
		        	    "cedJunc",
		        	    "icRej",
		        	    "icNot",
		        	    "coApe",
		        	    "coDsn",
		        	    "icArqDup",
		        	    "coCxPostal",
		        	    "coApeDupl",
		        	    "coDsnDup",
		        	    "nuUltRem",
		        	    "agrupEsc",
		        	    "dscAgrup",
		        	    "nuUltRet",
		        	    "dtCargaIni",
		        	    "connect",
		        	    "deConnect",
		        	    "situacao",
		        	    "internet",
		        	    "deInternet",
		        	    "icReto",
		        	    "nuUltReto",
		        	    "icRemOnline",
		        	    "icServicoWeb",
		        	    //---Guia Boletos
		        	    "tpEmisBloq",
		        	    "deEmisBloq",
		        	    "tpEntregaBloq",
		        	    "deEntregaBloq",
		        	    "tpEntregaSac",
		        	    "deEntregaSac",
		        	    "icAvisoVenc",
		        	    "icAvisoProt",
		        	    "vrMinAvis",
		        	    "qtdDiasProt",
		        	    "avisDisBloq1",
		        	    "avisDisBloq2",
		        	    "avisDisBloq3",
		        	    "avisVenc1",
		        	    "avisVenc2",
		        	    "avisVenc3",
		        	    "imprimeDDA",
		        	    "icEnvioSms",
		        	    "prazoSms1",
		        	    "prazoSms2",
		        	    "prazoSms3",
		        	    "qtdeBoleto",
		        	    "vrMinimo",
		        	    "vrMaximo",
		        	    //Guia Tarifas
		        	    "tipoPeriodo",
		        	    "dePeriodo",
		        	    "ddDebito",
		        	    "icFormaCalculo",
		        	    //-----Parametros
		        	    "tpCalc",
		        	    "autVrCob",
		        	    "garOpcrd",
		        	    "bolExpresso",
		        	    "limValor",
		        	    "creOnline",
		        	    "icClienteExterno",
		        	    "icFimDfrd",
		        	    "nuEvtContabil",
		        	    "icUndCrdo",
		        	    "icrateioTit",
		        	    "icCedGarantia",
		        	    "nuOpGarantia",
		        	    "nuContratoGarantia",
		        	    "icBaixaGar",
		        	    "icMrcGar",
		        	    "icDsmGar",
		        	    "icContaGar",
		        	    "nuUnidadeGar",
		        	    "nuOpGar",
		        	    "nuContagar",
		        	    "nuDvGar",
		        	    "icLncContabil",
		        	    "nuEventoContabil",
		        	    "icBolProposta",
		        	    "icCmdDebito",
		        	    "icCriticaCep",
		                "tpBeneficiario",
		                "cdEntidadeSindical",
		                "nuEventoContabilDebito",
		                "icAutorizaPgto",
		                "icCalcIndice",
		                "sgIndiceEspecial",
		                "icAplIndiceEspecial"

		        	        
        });
    }
}
